### ISSUE TITLE
Errors on some engine builds/mods

### ISSUE THREAD

**Issue by SNMetamorph** [SNMetamorph/goldsrc-monitor#1]
### Please, report in a specific format

1) Engine build number (from `version` console command)
2) Name of mod (for example, Counter-Strike, or Half-Life)
3) Link to main page of mod, if exists (usually, may be GameBanana or ModDB)
4) Error message text (from window which shown when error occured)
5) Note from you, if needed

**Comment by Vladislav4KZ** [comment]
Забудь, эта ошибка была из-за пропавшего build_info.json

Заново распаковал архив GoldSource Monitor, и он заработал

**Comment by hajimura** [comment]
1. `Protocol version 48`
`Exe version 1.1.2.7 (cstrike)`
`Exe build: 23:40:23 Dec 11 2023 (9909)`
2. Counter_Strike
3. [s1lent's client. Link](https://download-cs.net/cs/cs-1-6-novaya-versiya.php)
4. 
![Безымянный](https://github.com/SNMetamorph/goldsrc-monitor/assets/10776436/c6442edf-69d5-4502-9d0b-5ab24e09f644)
5. It would be great to add support of s1lent's client

**Comment by johan123kl** [comment]
1.
<img width="640" alt="version xash3d" src="https://github.com/SNMetamorph/goldsrc-monitor/assets/169866410/28426a21-2322-4fd9-98a8-03b82c0256dd">
2. xash3d fwgs
3. https://www.moddb.com/engines/xash3d-fwgs-engine/
4. 
<img width="737" alt="xash3d gsm" src="https://github.com/SNMetamorph/goldsrc-monitor/assets/169866410/e3c3a2b0-4cf6-4abb-ad7d-e69c9a248fa3">
5. its the lates version (sorry im bad at saying lates)

**Comment by SNMetamorph** [comment]
@johan123kl recheck it on latest Xash3D FWGS build, it should work
