### ISSUE TITLE
[Feature request] Add support for velocity when playing demos.

### ISSUE THREAD

**Issue by HannoMartinus** [SNMetamorph/goldsrc-monitor#12]
Hello, I'm wondering if it's possible to read the velocity of demos (the input from a recorded demo file)? If it's possible, and you're willing to add it, I'd like to request it.
Thanks in advance.

**Comment by SNMetamorph** [comment]
That's interesting idea. I'll check is it possible to do, and if it's possible I'll implement it.

**Comment by SNMetamorph** [comment]
Implemented in https://github.com/SNMetamorph/goldsrc-monitor/commit/5a85a7caf4fe4907f3d6366a59b68d84cbc1c399
