### ISSUE TITLE
Both nightly and stable build can't detect Xash3D-FWGS.

### ISSUE THREAD

**Issue by TheKingFireS** [SNMetamorph/goldsrc-monitor#17]
Engine build: Xash3D-FWGS 3051 commit: 0df89bddeb3e263cdc6595fadaf79e39b656bdd2
mod: Half-Life
both builds will show this same error, with different file cpp number line.

---------------------------
GoldSrc Monitor
---------------------------
ERROR [build_info.cpp:43]: failed to approximate engine build number

**Comment by SNMetamorph** [comment]
Thank you for reporting, I'll fix it when I get back to work

**Comment by SNMetamorph** [comment]
I guess this should be fixed in c7b391de2e7477e72dc42c11b7550555dfbf33a4. But there is one nuance - changes from commit https://github.com/FWGS/xash3d-fwgs/commit/8c351d92556f76630ad1d64fe2ceaa78f4a1be70 in engine was reverted in commit https://github.com/FWGS/xash3d-fwgs/commit/de1e53311a65400fc3e8d54daf3ebec5726d8e21. Therefore GoldSrc Monitor won't work with latest builds, and you should try other builds that created before this commit. Can you test it, please?

**Comment by TheKingFireS** [comment]
Still same error as before, already tried all method (reinstall, create separated folder, using latest version of both program)

info:
![image](https://github.com/SNMetamorph/goldsrc-monitor/assets/71936968/09a437be-ec8c-41e9-8461-23b1c21791ee)

```
---------------------------
GoldSrc Monitor
---------------------------
ERROR [client_module.cpp:53]: build info parsing error: failed to approximate engine build number
```

**Comment by SNMetamorph** [comment]
Which engine commit are you using?

**Comment by TheKingFireS** [comment]
Latest engine commit one, https://github.com/FWGS/xash3d-fwgs/commit/0aa8a2891cb52668ad62f6795fa5b26aea0df683

**Comment by SNMetamorph** [comment]
It won't work now, check my first comment here, I described why is it like this

**Comment by TheKingFireS** [comment]
Oh right.
It's worked when randomly picked and using build (https://github.com/FWGS/xash3d-fwgs/commit/8888b456df00c155f3713ea1b35742f6bdbc0aef) before https://github.com/FWGS/xash3d-fwgs/commit/de1e53311a65400fc3e8d54daf3ebec5726d8e21

**Comment by SNMetamorph** [comment]
Yes, it's correct. Therefore this issue fixed.

**Comment by SNMetamorph** [comment]
I submitted https://github.com/FWGS/xash3d-fwgs/pull/1481 that will fix working GoldSrc Monitor on latest builds of Xash3D FWGS soon.

**Comment by TheKingFireS** [comment]
Ok, cool.
