### ISSUE TITLE
Force -insecure flag when launching hl.exe

### ISSUE THREAD

**Issue by sabianroberts** [SNMetamorph/goldsrc-monitor#19]
Since this tool presents a risk of being flagged as a cheat-program by VAC, forcing the `-insecure` flag to be present when opening the game could help prevent accidental bans when developers test multiplayer mods in their own servers.

**Comment by SNMetamorph** [comment]
Thanks for your suggestion. To be honest, it is out of scope for this tool, because it does not have control over starting game process - what it does, is just attaches to existing running game process. So, there is no way we can control such things
